2018-05-14 12:49:28.110 +03:00 [Debug] initializing Sync...
2018-05-14 12:49:28.488 +03:00 [Debug] configured endpoint
2018-05-14 12:49:28.490 +03:00 [Debug] ----------------------------------------
2018-05-14 12:49:28.490 +03:00 [Debug]     http://localhost:3333
2018-05-14 12:49:28.490 +03:00 [Debug] ----------------------------------------
2018-05-14 12:49:28.491 +03:00 [Debug] configured connection
2018-05-14 12:49:28.491 +03:00 [Debug] ----------------------------------------
2018-05-14 12:49:28.492 +03:00 [Debug]     Data Source=.\KOSKE14;Initial Catalog=LiveHAPI;Persist Security Info=True;User ID=sa;Password=maun;MultipleActiveResultSets=True;Pooling=True
2018-05-14 12:49:28.492 +03:00 [Debug] ----------------------------------------
2018-05-14 12:49:29.021 +03:00 [Debug] starting Sync...
2018-05-14 12:49:29.243 +03:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2018-05-14 12:49:29.310 +03:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2018-05-14 12:49:29.323 +03:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2018-05-14 12:49:29.327 +03:00 [Information] Quartz Scheduler v."3.0.4.0" created.
2018-05-14 12:49:29.330 +03:00 [Information] RAMJobStore initialized.
2018-05-14 12:49:29.335 +03:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.0.4.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2018-05-14 12:49:29.336 +03:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2018-05-14 12:49:29.336 +03:00 [Information] Quartz scheduler version: 3.0.4.0
2018-05-14 12:49:29.346 +03:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2018-05-14 12:49:29.348 +03:00 [Debug] Sync started !
2018-05-14 12:49:29.350 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 12:49:29.367 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:29.376 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 12:49:29.383 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:29.386 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 12:49:29.387 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:29.390 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 12:49:29.391 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 12:49:29.402 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 12:49:29.402 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 12:49:29.402 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 12:49:31.321 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:31.327 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:31.418 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:31.419 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:31.574 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:31.576 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:44.353 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 12:49:44.355 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 12:49:44.355 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:44.365 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 12:49:44.366 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:44.366 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 12:49:44.373 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 12:49:44.374 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 12:49:44.374 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 12:49:44.399 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:44.400 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:44.731 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:44.732 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:44.890 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:44.891 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:59.351 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 12:49:59.353 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 12:49:59.353 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:59.365 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 12:49:59.366 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:59.366 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 12:49:59.373 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 12:49:59.373 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 12:49:59.373 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 12:49:59.388 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:59.389 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:59.567 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:59.568 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:49:59.908 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:49:59.909 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:14.351 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 12:50:14.353 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 12:50:14.353 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:14.365 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 12:50:14.366 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 12:50:14.366 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:14.373 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 12:50:14.374 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 12:50:14.374 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 12:50:14.639 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:50:14.640 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:14.763 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:50:14.764 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:15.423 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:50:15.424 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:29.352 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 12:50:29.355 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 12:50:29.355 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:29.365 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 12:50:29.365 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 12:50:29.365 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:29.373 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 12:50:29.374 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 12:50:29.374 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 12:50:29.387 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:50:29.388 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:29.550 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:50:29.552 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 12:50:29.945 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 12:50:29.946 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:34:56.015 +03:00 [Debug] initializing Sync...
2018-05-14 14:34:56.353 +03:00 [Debug] configured endpoint
2018-05-14 14:34:56.354 +03:00 [Debug] ----------------------------------------
2018-05-14 14:34:56.355 +03:00 [Debug]     http://localhost:3333
2018-05-14 14:34:56.355 +03:00 [Debug] ----------------------------------------
2018-05-14 14:34:56.355 +03:00 [Debug] configured connection
2018-05-14 14:34:56.356 +03:00 [Debug] ----------------------------------------
2018-05-14 14:34:56.356 +03:00 [Debug]     Data Source=.\KOSKE14;Initial Catalog=LiveHAPI;Persist Security Info=True;User ID=sa;Password=maun;MultipleActiveResultSets=True;Pooling=True
2018-05-14 14:34:56.357 +03:00 [Debug] ----------------------------------------
2018-05-14 14:34:56.907 +03:00 [Debug] starting Sync...
2018-05-14 14:34:57.140 +03:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2018-05-14 14:34:57.198 +03:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2018-05-14 14:34:57.219 +03:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2018-05-14 14:34:57.223 +03:00 [Information] Quartz Scheduler v."3.0.4.0" created.
2018-05-14 14:34:57.227 +03:00 [Information] RAMJobStore initialized.
2018-05-14 14:34:57.231 +03:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.0.4.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2018-05-14 14:34:57.232 +03:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2018-05-14 14:34:57.232 +03:00 [Information] Quartz scheduler version: 3.0.4.0
2018-05-14 14:34:57.240 +03:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2018-05-14 14:34:57.242 +03:00 [Debug] Sync started !
2018-05-14 14:34:57.245 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:34:57.260 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:34:57.267 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:34:57.274 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:34:57.277 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:34:57.277 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:34:57.280 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:34:57.281 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:34:57.294 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:34:57.294 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:34:57.294 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:35:00.488 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:35:00.488 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:35:00.488 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:35:00.574 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:00.574 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:00.574 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:00.640 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:00.640 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:00.646 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:00.651 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:00.732 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:00.733 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:12.248 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:35:12.264 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:35:12.264 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:12.283 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:35:12.287 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:35:12.287 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:12.307 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:35:12.313 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:35:12.313 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:35:16.914 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:35:17.090 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:35:17.090 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:35:17.106 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:17.129 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:17.122 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:17.148 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:17.133 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:17.167 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:17.113 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:17.202 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:17.208 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:27.248 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:35:27.254 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:35:27.254 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:27.294 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:35:27.308 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:27.314 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:35:27.322 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:35:27.322 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:35:27.308 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:35:31.656 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:35:31.852 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:35:31.852 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:35:31.868 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:31.880 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:31.900 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:31.904 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:31.874 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:31.895 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:31.937 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:31.942 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:31.944 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:42.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:35:42.252 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:35:42.252 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:42.274 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:35:42.280 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:42.286 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:35:42.292 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:35:42.292 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:35:42.280 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:35:46.506 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:35:46.632 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:35:46.632 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:35:46.640 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:46.642 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:46.652 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:46.654 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:46.647 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:35:46.650 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:46.668 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:46.674 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:35:46.676 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:57.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:35:57.249 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:35:57.249 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:57.260 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:35:57.262 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:35:57.266 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:35:57.269 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:35:57.269 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:35:57.262 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:36:01.434 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:36:01.493 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:36:01.442 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:36:01.497 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:01.499 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:01.501 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:01.502 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:01.501 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:01.504 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:01.498 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:01.508 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:01.511 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:12.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:36:12.249 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:36:12.249 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:12.260 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:36:12.263 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:36:12.263 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:12.276 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:36:12.277 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:36:12.277 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:36:16.649 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:36:16.664 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:36:16.696 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:16.705 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:16.692 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:36:16.706 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:16.704 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:16.715 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:16.715 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:16.711 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:16.722 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:16.723 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:27.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:36:27.247 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:36:27.248 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:27.259 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:36:27.261 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:36:27.261 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:27.265 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:36:27.265 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:36:27.266 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:36:31.398 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:36:31.445 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:36:31.449 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:31.451 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:31.452 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:31.445 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:36:31.456 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:31.450 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:31.460 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:31.461 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:31.458 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:31.466 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:42.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:36:42.247 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:36:42.247 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:42.259 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:36:42.260 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:36:42.260 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:42.264 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:36:42.264 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:36:42.264 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:36:44.329 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:36:44.333 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:44.335 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:44.336 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:46.402 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:36:46.410 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:36:46.414 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:46.416 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:46.418 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:46.418 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:46.417 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:46.425 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:57.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:36:57.248 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:36:57.249 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:57.260 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:36:57.260 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:36:57.260 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:36:57.262 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:36:57.263 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:36:57.263 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:36:59.328 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:36:59.332 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:36:59.334 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:36:59.335 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:01.397 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:37:01.397 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:37:01.400 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:01.402 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:01.403 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:01.403 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:01.407 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:01.407 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:12.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:37:12.248 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:37:12.249 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:12.259 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:37:12.261 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:37:12.261 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:12.268 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:37:12.268 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:37:12.268 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:37:14.327 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:37:14.330 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:14.332 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:14.333 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:16.383 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:37:16.399 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:37:16.403 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:16.405 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:16.405 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:16.408 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:16.408 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:16.409 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:27.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:37:27.248 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:37:27.249 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:27.259 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:37:27.262 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:27.263 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:37:27.263 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:37:27.262 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:37:27.263 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:37:31.388 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:37:31.424 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:37:31.476 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:37:31.480 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:31.482 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:31.484 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:31.487 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:31.480 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:31.491 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:31.491 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:31.486 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:31.494 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:42.246 +03:00 [Debug] Producing instance of Job 'jSyncFacilitiesJobgroup.jSyncFacilitiesJob', class=LiveHAPI.Sync.Jobs.SyncFacilitiesJob
2018-05-14 14:37:42.249 +03:00 [Debug] Calling Execute on job jSyncFacilitiesJobgroup.jSyncFacilitiesJob
2018-05-14 14:37:42.249 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:42.259 +03:00 [Debug] Producing instance of Job 'jSyncUsersJobgroup.jSyncUsersJob', class=LiveHAPI.Sync.Jobs.SyncUsersJob
2018-05-14 14:37:42.261 +03:00 [Debug] Calling Execute on job jSyncUsersJobgroup.jSyncUsersJob
2018-05-14 14:37:42.261 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:42.265 +03:00 [Debug] Producing instance of Job 'jSyncLookupsJobgroup.jSyncLookupsJob', class=LiveHAPI.Sync.Jobs.SyncLookupsJob
2018-05-14 14:37:42.265 +03:00 [Debug] Batch acquisition of 0 triggers
2018-05-14 14:37:42.265 +03:00 [Debug] Calling Execute on job jSyncLookupsJobgroup.jSyncLookupsJob
2018-05-14 14:37:46.384 +03:00 [Error] error reading endpint [api/setup/getFacilities] for ClientFacility
2018-05-14 14:37:46.476 +03:00 [Error] error reading endpint [api/setup/htsOptions] for ClientLookup
2018-05-14 14:37:46.423 +03:00 [Error] error reading endpint [api/setup/getUsers] for ClientUser
2018-05-14 14:37:46.484 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:46.486 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:46.487 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:46.488 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:46.488 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:46.484 +03:00 [Error] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LiveHAPI.Sync.Core.Reader.ClientReader`1.<Read>d__3.MoveNext() in E:\Workspace\Palladium\hts\LiveHAPI\LiveHAPI.Sync.Core\Reader\ClientReader.cs:line 30
2018-05-14 14:37:46.496 +03:00 [Debug] Trigger instruction : NoInstruction
2018-05-14 14:37:46.491 +03:00 [Debug] Batch acquisition of 1 triggers
2018-05-14 14:37:46.499 +03:00 [Debug] Batch acquisition of 1 triggers
